apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: eks-node-alerts
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: kube-prometheus-stack
spec:
  groups:
  - name: eks-nodes
    rules:
    # 수정: 올바른 job 라벨 사용
    - alert: EKSNodeExporterDown
      expr: up{job="node-exporter"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "EKS 노드 Exporter 다운"
        description: "노드 {{ $labels.instance }}의 Node Exporter가 5분 이상 다운되었습니다."

    # 기존 설정 유지 (정상)
    - alert: EKSNodeHighCPUUsage
      expr: |
        (
          100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
        ) > 80
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "EKS 노드 높은 CPU 사용률"
        description: "노드 {{ $labels.instance }}의 CPU 사용률이 높습니다: {{ $value | humanizePercentage }}."

    # 기존 설정 유지 (정상)
    - alert: EKSNodeHighMemoryUsage
      expr: |
        (
          (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes
        ) > 0.85
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "EKS 노드 높은 메모리 사용률"
        description: "노드 {{ $labels.instance }}의 메모리 사용률이 높습니다: {{ $value | humanizePercentage }}."

    # 개선: 중요 마운트포인트만 모니터링
    - alert: EKSNodeLowDiskSpace
      expr: |
        (
          (node_filesystem_size_bytes{fstype!="tmpfs",mountpoint=~"/|/var/lib/.*"} - node_filesystem_avail_bytes{fstype!="tmpfs",mountpoint=~"/|/var/lib/.*"}) 
          / node_filesystem_size_bytes{fstype!="tmpfs",mountpoint=~"/|/var/lib/.*"}
        ) > 0.85
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "EKS 노드 낮은 디스크 공간"
        description: "노드 {{ $labels.instance }}의 {{ $labels.mountpoint }}에 디스크 공간이 부족합니다: {{ $value | humanizePercentage }} 사용됨."

    # 기존 설정 유지 (정상)
    - alert: EKSNodeHighDiskIOUtilization
      expr: rate(node_disk_io_time_seconds_total[5m]) > 0.8
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "EKS 노드 높은 디스크 I/O 사용률"
        description: "노드 {{ $labels.instance }}의 {{ $labels.device }}에서 디스크 I/O 사용률이 높습니다: {{ $value | humanizePercentage }}."

    # 기존 설정 유지 (정상)
    - alert: EKSNodeHighLoadAverage
      expr: node_load5 / on(instance) count by (instance) (node_cpu_seconds_total{mode="idle"}) > 2
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "EKS 노드 높은 로드 평균"
        description: "노드 {{ $labels.instance }}의 로드 평균이 높습니다: {{ $value }}."

    # 개선: 실제 네트워크 인터페이스만 모니터링
    - alert: EKSNodeNetworkReceiveErrors
      expr: rate(node_network_receive_errs_total{device!~"lo|veth.*|docker.*|br-.*"}[5m]) > 0.01
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "EKS 노드 네트워크 수신 에러"
        description: "노드 {{ $labels.instance }}의 {{ $labels.device }}에서 네트워크 수신 에러가 발생했습니다: {{ $value }} 에러/초."

    # 개선: 실제 네트워크 인터페이스만 모니터링
    - alert: EKSNodeNetworkTransmitErrors
      expr: rate(node_network_transmit_errs_total{device!~"lo|veth.*|docker.*|br-.*"}[5m]) > 0.01
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "EKS 노드 네트워크 전송 에러"
        description: "노드 {{ $labels.instance }}의 {{ $labels.device }}에서 네트워크 전송 에러가 발생했습니다: {{ $value }} 에러/초."

    # 수정: 올바른 파드 용량 계산
    - alert: EKSNodePodCapacityHigh
      expr: |
        (
          count by (node) (kube_pod_info{node!=""}) 
          / on(node) 
          kube_node_status_allocatable{resource="pods"}
        ) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "EKS 노드 높은 파드 용량 사용률"
        description: "노드 {{ $labels.node }}의 파드 용량 사용률이 {{ $value | humanizePercentage }}입니다."

    # 기존 설정 유지 (정상)
    - alert: EKSNodeNotReady
      expr: kube_node_status_condition{condition="Ready",status="false"} == 1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "EKS 노드 준비되지 않음"
        description: "노드 {{ $labels.node }}가 5분 이상 준비되지 않았습니다."

    # 기존 설정 유지 (정상)
    - alert: EKSNodeUnschedulable
      expr: kube_node_spec_unschedulable == 1
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: "EKS 노드 스케줄링 불가"
        description: "노드 {{ $labels.node }}가 스케줄링 불가능한 상태입니다."

    # 추가: Kubelet 상태 모니터링 (별도 알림)
    - alert: EKSKubeletDown
      expr: up{job="kubelet"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "EKS Kubelet 다운"
        description: "노드 {{ $labels.node }}의 Kubelet이 5분 이상 다운되었습니다."

    # 추가: Node Exporter 메트릭 부재 감지
    - alert: EKSNodeMetricsAbsent
      expr: absent(node_load1)
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "EKS 노드 메트릭 수집 실패"
        description: "노드 시스템 메트릭이 5분 이상 수집되지 않고 있습니다."