apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: eks-deployment-alerts
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: kube-prometheus-stack
spec:
  groups:
  - name: eks-deployments
    rules:
    # 디플로이먼트 핵심 알림
    - alert: EKSDeploymentDown
      expr: kube_deployment_status_replicas_available{namespace!="kube-system"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "EKS 디플로이먼트 완전 중단"
        description: "네임스페이스 {{ $labels.namespace }}의 디플로이먼트 {{ $labels.deployment }}에 사용 가능한 레플리카가 없습니다."

    - alert: EKSDeploymentReplicasMismatch
      expr: |
        (
          kube_deployment_status_replicas_available{namespace!="kube-system"}
          != 
          kube_deployment_spec_replicas{namespace!="kube-system"}
        )
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "EKS 디플로이먼트 레플리카 불일치"
        description: "네임스페이스 {{ $labels.namespace }}의 디플로이먼트 {{ $labels.deployment }}에서 사용 가능한 레플리카({{ $labels.status_replicas_available }})가 원하는 수({{ $labels.spec_replicas }})와 다릅니다."

    - alert: EKSDeploymentRolloutStuck
      expr: |
        kube_deployment_status_condition{condition="Progressing", status="false", namespace!="kube-system"} == 1
      for: 15m
      labels:
        severity: critical
      annotations:
        summary: "EKS 디플로이먼트 롤아웃 중단"
        description: "네임스페이스 {{ $labels.namespace }}의 디플로이먼트 {{ $labels.deployment }} 롤아웃이 15분 이상 중단되었습니다."

    - alert: EKSDeploymentOldReplicaSet
      expr: |
        (
          kube_deployment_status_replicas_updated{namespace!="kube-system"}
          < 
          kube_deployment_spec_replicas{namespace!="kube-system"}
        )
      for: 20m
      labels:
        severity: warning
      annotations:
        summary: "EKS 디플로이먼트 구 버전 레플리카셋 잔존"
        description: "네임스페이스 {{ $labels.namespace }}의 디플로이먼트 {{ $labels.deployment }}에서 구 버전 레플리카셋이 20분 이상 남아있습니다."

    # 파드 상태 알림 (디플로이먼트 한정)
    - alert: EKSPodNotReady
      expr: |
        kube_pod_status_ready{condition="false", namespace!="kube-system"} == 1
        and on(namespace, pod)
        kube_pod_info{created_by_kind="ReplicaSet"}
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "EKS 디플로이먼트 파드 준비되지 않음"
        description: "네임스페이스 {{ $labels.namespace }}의 파드 {{ $labels.pod }}가 15분 이상 준비되지 않았습니다."

    - alert: EKSPodFrequentRestart
      expr: |
        increase(kube_pod_container_status_restarts_total{namespace!="kube-system"}[1h]) > 5
        and on(namespace, pod)
        kube_pod_info{created_by_kind="ReplicaSet"}
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: "EKS 디플로이먼트 파드 빈번한 재시작"
        description: "네임스페이스 {{ $labels.namespace }}의 파드 {{ $labels.pod }}가 지난 1시간 동안 {{ $value }}번 재시작되었습니다."

    - alert: EKSPodCrashLooping
      expr: |
        rate(kube_pod_container_status_restarts_total{namespace!="kube-system"}[15m]) > 0.1
        and on(namespace, pod)
        kube_pod_info{created_by_kind="ReplicaSet"}
      for: 15m
      labels:
        severity: critical
      annotations:
        summary: "EKS 디플로이먼트 파드 크래시 루프"
        description: "네임스페이스 {{ $labels.namespace }}의 파드 {{ $labels.pod }}가 크래시 루프 상태입니다."

    - alert: EKSPodPendingTooLong
      expr: |
        kube_pod_status_phase{phase="Pending", namespace!="kube-system"} == 1
        and on(namespace, pod)
        kube_pod_info{created_by_kind="ReplicaSet"}
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "EKS 디플로이먼트 파드 장시간 대기"
        description: "네임스페이스 {{ $labels.namespace }}의 파드 {{ $labels.pod }}가 10분 이상 Pending 상태입니다."

    - alert: EKSPodImagePullError
      expr: |
        kube_pod_container_status_waiting{namespace!="kube-system"} == 1
        and on(namespace, pod)
        kube_pod_info{created_by_kind="ReplicaSet"}
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "EKS 디플로이먼트 파드 컨테이너 대기 중"
        description: "네임스페이스 {{ $labels.namespace }}의 파드 {{ $labels.pod }}의 컨테이너 {{ $labels.container }}가 10분 이상 대기 중입니다."

    # 추가: 디플로이먼트 스케일링 관련
    - alert: EKSDeploymentScaledToZero
      expr: |
        kube_deployment_spec_replicas{namespace!="kube-system"} == 0
        and
        kube_deployment_status_replicas_available{namespace!="kube-system"} == 0
      for: 30m
      labels:
        severity: info
      annotations:
        summary: "EKS 디플로이먼트 스케일 다운"
        description: "네임스페이스 {{ $labels.namespace }}의 디플로이먼트 {{ $labels.deployment }}가 0으로 스케일 다운되었습니다."

    - alert: EKSDeploymentHighReplicaCount
      expr: |
        kube_deployment_spec_replicas{namespace!="kube-system"} > 20
      for: 10m
      labels:
        severity: info
      annotations:
        summary: "EKS 디플로이먼트 높은 레플리카 수"
        description: "네임스페이스 {{ $labels.namespace }}의 디플로이먼트 {{ $labels.deployment }}가 {{ $value }}개의 레플리카를 가지고 있습니다."