apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: eks-pod-alerts
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: kube-prometheus-stack
spec:
  groups:
  - name: eks-pods
    rules:
    # 정상 동작 알림들 (그대로 유지)
    - alert: EKSPodNotReady
      expr: kube_pod_status_ready{condition="false", namespace!="kube-system"} == 1
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "EKS 파드 준비되지 않음"
        description: "네임스페이스 {{ $labels.namespace }}의 파드 {{ $labels.pod }}가 15분 이상 준비되지 않았습니다."

    - alert: EKSPodFrequentRestart
      expr: increase(kube_pod_container_status_restarts_total{namespace!="kube-system"}[1h]) > 5
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: "EKS 파드 빈번한 재시작"
        description: "네임스페이스 {{ $labels.namespace }}의 파드 {{ $labels.pod }}가 지난 1시간 동안 {{ $value }}번 재시작되었습니다."

    # 개선: 임계값 조정
    - alert: EKSPodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total{namespace!="kube-system"}[15m]) > 0.1
      for: 15m
      labels:
        severity: critical
      annotations:
        summary: "EKS 파드 크래시 루프"
        description: "네임스페이스 {{ $labels.namespace }}의 파드 {{ $labels.pod }}가 크래시 루프 상태입니다."

    - alert: EKSPodPending
      expr: kube_pod_status_phase{phase="Pending", namespace!="kube-system"} == 1
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "EKS 파드 대기 상태 고착"
        description: "네임스페이스 {{ $labels.namespace }}의 파드 {{ $labels.pod }}가 10분 이상 대기 상태입니다."

    - alert: EKSPodFailed
      expr: kube_pod_status_phase{phase="Failed", namespace!="kube-system"} == 1
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: "EKS 파드 실패"
        description: "네임스페이스 {{ $labels.namespace }}의 파드 {{ $labels.pod }}가 실패했습니다."

    # 대안: 기본 컨테이너 상태 모니터링 (reason 없이)
    - alert: EKSPodContainerNotRunning
      expr: |
        kube_pod_container_status_running{namespace!="kube-system"} == 0
        and
        kube_pod_status_phase{phase="Running"} == 1
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "파드 컨테이너가 실행되지 않음"
        description: "파드 {{ $labels.pod }}의 컨테이너 {{ $labels.container }} (네임스페이스: {{ $labels.namespace }})가 10분 이상 실행되지 않고 있습니다."

    - alert: EKSPodContainerWaiting
      expr: |
        kube_pod_container_status_waiting{namespace!="kube-system"} == 1
        and
        kube_pod_status_phase{phase="Pending"} == 1
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "컨테이너 대기 상태"
        description: "파드 {{ $labels.pod }}의 컨테이너 {{ $labels.container }} (네임스페이스: {{ $labels.namespace }})가 10분 이상 대기 중입니다."

    - alert: EKSPodContainerTerminated
      expr: |
        kube_pod_container_status_terminated{namespace!="kube-system"} == 1
        and
        kube_pod_status_phase{phase="Running"} == 1
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: "컨테이너가 예기치 않게 종료됨"
        description: "파드 {{ $labels.pod }}의 컨테이너 {{ $labels.container }} (네임스페이스: {{ $labels.namespace }})가 종료되었습니다."

    # 추가: 파드 스케줄링 실패 감지 (대안)
    - alert: EKSPodSchedulingFailure
      expr: |
        kube_pod_status_phase{phase="Pending", namespace!="kube-system"} == 1
        and
        kube_pod_status_ready{condition="false"} == 1
      for: 15m
      labels:
        severity: critical
      annotations:
        summary: "파드 스케줄링 실패"
        description: "파드 {{ $labels.pod }} (네임스페이스: {{ $labels.namespace }})가 15분 이상 스케줄링되지 않고 있습니다."