apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: eks-pod-alerts
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: kube-prometheus-stack
spec:
  groups:
  - name: eks-pods
    rules:
    - alert: EKSPodNotReady
      expr: kube_pod_status_ready{condition="false"} == 1
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "EKS 파드 준비되지 않음"
        description: "네임스페이스 {{ $labels.namespace }}의 파드 {{ $labels.pod }}가 15분 이상 준비되지 않았습니다."

    - alert: EKSPodFrequentRestart
      expr: increase(kube_pod_container_status_restarts_total[1h]) > 5
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: "EKS 파드 빈번한 재시작"
        description: "네임스페이스 {{ $labels.namespace }}의 파드 {{ $labels.pod }}가 지난 1시간 동안 {{ $value }}번 재시작되었습니다."

    - alert: EKSPodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
      for: 15m
      labels:
        severity: critical
      annotations:
        summary: "EKS 파드 크래시 루프"
        description: "네임스페이스 {{ $labels.namespace }}의 파드 {{ $labels.pod }}가 크래시 루프 상태입니다."

    - alert: EKSPodPending
      expr: kube_pod_status_phase{phase="Pending"} == 1
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "EKS 파드 대기 상태 고착"
        description: "네임스페이스 {{ $labels.namespace }}의 파드 {{ $labels.pod }}가 10분 이상 대기 상태입니다."

    - alert: EKSPodFailed
      expr: kube_pod_status_phase{phase="Failed"} == 1
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: "EKS 파드 실패"
        description: "네임스페이스 {{ $labels.namespace }}의 파드 {{ $labels.pod }}가 실패했습니다."

    - alert: EKSPodUnschedulable
      expr: kube_pod_status_unschedulable == 1
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "EKS 파드 스케줄링 불가"
        description: "네임스페이스 {{ $labels.namespace }}의 파드 {{ $labels.pod }}가 스케줄링될 수 없습니다."

    - alert: EKSPodContainerWaiting
      expr: kube_pod_container_status_waiting_reason{reason!="ContainerCreating"} == 1
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "EKS 파드 컨테이너 대기 중"
        description: "파드 {{ $labels.pod }}의 컨테이너 {{ $labels.container }} (네임스페이스: {{ $labels.namespace }})가 10분 이상 대기 중입니다. 사유: {{ $labels.reason }}"

    - alert: EKSPodImagePullBackOff
      expr: kube_pod_container_status_waiting_reason{reason="ImagePullBackOff"} == 1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "EKS 파드 이미지 풀 에러"
        description: "파드 {{ $labels.pod }}의 컨테이너 {{ $labels.container }} (네임스페이스: {{ $labels.namespace }})에서 이미지를 가져올 수 없습니다."

    - alert: EKSPodOOMKilled
      expr: kube_pod_container_status_terminated_reason{reason="OOMKilled"} == 1
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: "EKS 파드 컨테이너 OOM으로 종료"
        description: "파드 {{ $labels.pod }}의 컨테이너 {{ $labels.container }} (네임스페이스: {{ $labels.namespace }})가 메모리 부족으로 종료되었습니다."