apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: eks-service-alerts
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: kube-prometheus-stack
spec:
  groups:
  - name: eks-services
    rules:
    # 기본 서비스 모니터링 (실제 동작 가능)
    - alert: EKSServiceNoEndpoints
      expr: |
        kube_service_info{type!="ExternalName", namespace!="kube-system"}
        unless on(namespace, service)
        kube_endpoint_address_available
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "EKS 서비스 엔드포인트 없음"
        description: "네임스페이스 {{ $labels.namespace }}의 서비스 {{ $labels.service }}에 사용 가능한 엔드포인트가 없습니다."

    # LoadBalancer 서비스 모니터링 (개선)
    - alert: EKSLoadBalancerServiceDown
      expr: |
        kube_service_info{cluster_ip!="None", namespace!="kube-system"}
        unless on(namespace, service)
        kube_endpoint_address_available
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "EKS LoadBalancer 서비스 엔드포인트 없음"
        description: "네임스페이스 {{ $labels.namespace }}의 LoadBalancer 서비스 {{ $labels.service }}에 엔드포인트가 없습니다."

    # 인그레스 모니터링 (kube-state-metrics 기반)
    - alert: EKSIngressBackendDown
      expr: |
        kube_ingress_info{namespace!="kube-system"}
        unless on(namespace)
        kube_endpoint_address_available
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "EKS 인그레스 백엔드 다운"
        description: "네임스페이스 {{ $labels.namespace }}의 인그레스 {{ $labels.ingress }}의 백엔드가 사용할 수 없습니다."

    # 조건부: blackbox-exporter 사용시만 
    # - alert: EKSIngressCertificateExpiry
    #   expr: (probe_ssl_earliest_cert_expiry - time()) / 86400 < 30
    #   for: 0m
    #   labels:
    #     severity: warning
    #   annotations:
    #     summary: "EKS 인그레스 인증서 곧 만료"
    #     description: "인그레스 인증서가 {{ $value }}일 후 만료됩니다."

    # 조건부: Istio 사용시만 
    # - alert: EKSServiceMeshSidecarNotReady
    #   expr: |
    #     kube_pod_container_status_ready{container="istio-proxy", namespace!="kube-system"} == 0
    #     and on(namespace, pod)
    #     kube_pod_info{created_by_kind="ReplicaSet"}
    #   for: 5m
    #   labels:
    #     severity: warning
    #   annotations:
    #     summary: "서비스 메시 사이드카 준비되지 않음"
    #     description: "파드 {{ $labels.pod }}의 Istio 사이드카가 준비되지 않았습니다."